# -*- coding: utf-8 -*-
"""Deutschlandincome.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wUEJuKoElhAoLrJdxnxOrdBinJ2KdmmS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('germanincome.xlsx')
df.drop(index=[0,1,2,3,80,81,82,83,84],axis=0,inplace=True)
names = ["Jahre","Haushaltsbruttoeinkommen","scale","Alleinerziehende","Ehepaare","Insgesamt"]
df.columns = names
df

df

df = df.set_index('Jahre')

df = df.drop(['Erfasste Haushalte','Hochgerechnete Haushalte'])
df

df_1 = df.T.pop('Durchschnittsbetrag je Haushalt und Monat').T
df_1 = df_1.reset_index()
df_1 = df_1.drop(['Jahre'],axis = 1)
df_1

df = df.drop(['Durchschnittsbetrag je Haushalt und Monat'])
#df = df.pop('s')
df

df.reset_index(inplace=True)
df

df.drop(['Haushaltsbruttoeinkommen','scale','Alleinerziehende','Ehepaare','Insgesamt'],axis=1,inplace = True)
df

final = pd.concat([df,df_1], axis=1)

final.drop(['Haushaltsbruttoeinkommen','scale'],axis = 1,inplace = True)
final

final['Alleinerziehende pro Jahr'] = (final['Alleinerziehende']*12)
final['Ehepaare pro Jahr'] = (final['Ehepaare']*12)
final['Insgesamt pro Jahr'] = (final['Insgesamt']*12)
final

final.drop(['Alleinerziehende','Ehepaare','Insgesamt'],axis = 1,inplace = True)
final

final = final.set_index('Jahre')
final

cols = final.columns.to_list()
cols = cols[-1:] + cols[:-1]
final = final[cols]

final.rename(columns = {'Insgesamt pro Jahr':'Alle','Alleinerziehende pro Jahr':'Alleinerziehende mit Kinder','Ehepaare pro Jahr':'Kernfamilie'}, inplace = True)

final.plot(title='Durchschnittliche Einkommen der Haushalte pro Jahr in Deutschland',xlabel='Jahre',ylabel='EUR',legend=True,figsize=(12, 6))

final.plot.bar(title='Durchschnittliche Einkommen der Haushalte pro Jahr in Deutschland',xlabel='Jahre',ylabel='EUR',legend=True,figsize=(12, 6))

final

final['Anteil Alleinerziehende von Alle'] = (final['Alleinerziehende mit Kinder'] / final['Alle']*100)
final['Anteil Alleinerziehende von Kernfamilie'] = (final['Alleinerziehende mit Kinder'] / final['Kernfamilie']*100)
final.astype(float)

df_2 = final[['Anteil Alleinerziehende von Alle','Anteil Alleinerziehende von Kernfamilie']].copy()
df_2 = df_2.astype('float64')
df_2.dtypes

df_2['Anteil Alleinerziehende von Alle'] = df_2['Anteil Alleinerziehende von Alle'].round(decimals = 2)
df_2['Anteil Alleinerziehende von Kernfamilie'] = df_2['Anteil Alleinerziehende von Kernfamilie'].round(decimals = 2)
df_2

