# -*- coding: utf-8 -*-
"""Taiwanincome.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rACHQSyfScLQZUme9mZz-RuMjbi452Yl
"""

import xml.etree.ElementTree as XET
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

tree = XET.parse('taiwanincome.xml')
root = tree.getroot() 
for child in root:
  for i in child:
    print(i.tag, i.attrib)

print(root[0][1].text)

sp_income = []
nu_income = []
twa_income = []
year = []
for data in root.findall('Data'):
    sp = data.find('單親家庭').text
    sp_income.append(sp)
    nu = data.find('核心家庭').text
    nu_income.append(nu)
    twa = data.find('臺灣地區').text
    twa_income.append(twa)
    y = data.find('Year').text
    year.append(y)

del year[0:2]
year

del sp_income[0:2]
sp_income

del twa_income[0:2]
twa_income

del nu_income[0:2]
nu_income

zipped_list = zip(year,twa_income,sp_income,nu_income)
zipped_list = list(zipped_list)

df = pd.DataFrame(zipped_list)
df
column = ["Jahre","Alle","Alleinerziehende mit Kinder","Kernfamilie"]
df.columns = column
df
df.set_index('Jahre', inplace=True)
df
df=df.astype(float)
#df['Anteil Alleinerziehende von Alle'] = (df['Alleinerziehende mit Kinder'] / df['Alle'])
#df['Anteil Alleinerziehende von Kernfamilie'] = (df['Alleinerziehende mit Kinder'] / df['Kernfamilie'])
df

df=df.astype(float)

chart = df.plot(title='Durchschnittliche Einkommen der Haushalte pro Jahr in Taiwan',xlabel='Jahre',ylabel='TWD(Million)',legend=True,figsize=(12, 6))

df.plot.bar(title='Durchschnittliche Einkommen der Haushalte pro Jahr in Taiwan',xlabel='Jahre',ylabel='TWD(Million)',legend=True,figsize=(12, 6))

df
df=df.astype(float)
df['Anteil Alleinerziehende von Alle'] = (df['Alleinerziehende mit Kinder'] / df['Alle']*100)
df['Anteil Alleinerziehende von Kernfamilie'] = (df['Alleinerziehende mit Kinder'] / df['Kernfamilie']*100)
df

df_2 = df[['Anteil Alleinerziehende von Alle','Anteil Alleinerziehende von Kernfamilie']].copy()
df_2.dtypes

df_2['Anteil Alleinerziehende von Alle'] = df_2['Anteil Alleinerziehende von Alle'].round(decimals = 2)
df_2['Anteil Alleinerziehende von Kernfamilie'] = df_2['Anteil Alleinerziehende von Kernfamilie'].round(decimals = 2)
df_2